# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180818_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('idClip', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('seg_initial', models.BigIntegerField()),
                ('seg_final', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='clips',
            field=models.ManyToManyField(to='gallery.Clip'),
        ),
    ]
