# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180826_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='fec_create',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
