# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='clips',
            field=models.ManyToManyField(blank=True, to='gallery.Clip'),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaType',
            field=models.CharField(choices=[('Video', 'VIDEO'), ('Audio', 'AUDIO')], default='Video', max_length=10),
        ),
    ]
