# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_media_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
