# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20180901_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='clips',
        ),
        migrations.AddField(
            model_name='clip',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Media'),
        ),
        migrations.AddField(
            model_name='clip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
