# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='clips',
        ),
        migrations.AddField(
            model_name='clip',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Media'),
        ),
        migrations.AddField(
            model_name='clip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.User'),
        ),
    ]
